# Generated by Django 5.2 on 2025-04-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='المفتاح (مثلاً about, services)')),
                ('title_ar', models.CharField(max_length=200, verbose_name='العنوان (عربي)')),
                ('title_en', models.CharField(max_length=200, verbose_name='العنوان (إنجليزي)')),
                ('description_ar', models.TextField(verbose_name='الوصف (عربي)')),
                ('description_en', models.TextField(verbose_name='الوصف (إنجليزي)')),
            ],
        ),
    ]
