# Generated by Django 5.2 on 2025-05-04 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=100)),
                ('title_ar', models.CharField(max_length=100)),
                ('description_en', models.TextField()),
                ('description_ar', models.TextField()),
                ('level', models.CharField(choices=[('Manager', 'مدير'), ('Eng', 'مهندس'), ('Tech', 'فني'), ('Emp', 'موظف')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255)),
                ('name_ar', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='emp')),
                ('date_joined', models.DateField()),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.job')),
            ],
        ),
    ]
