# Generated by Django 5.2 on 2025-05-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_employee_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name_ar', models.CharField(max_length=255)),
                ('company_name_en', models.CharField(max_length=255)),
                ('service_title_ar', models.CharField(max_length=255)),
                ('service_title_en', models.CharField(max_length=255)),
                ('service_description_ar', models.TextField()),
                ('service_description_en', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='company_works/')),
                ('video', models.FileField(blank=True, null=True, upload_to='company_works/videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
