# Generated by Django 5.2.1 on 2025-06-03 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_employee_residency_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255, verbose_name='اسم السجل بالعربي')),
                ('name_en', models.CharField(max_length=255, verbose_name='اسم السجل بالإنجليزي')),
                ('start_date', models.DateField(null=True, verbose_name='بداية السجل')),
                ('end_date', models.DateField(null=True, verbose_name='نهاية السجل')),
                ('file', models.FileField(blank=True, null=True, upload_to='licenses/', verbose_name='الملف')),
                ('unified_number', models.CharField(max_length=100, unique=True, verbose_name='رقم الموحد للسجل')),
                ('license_number', models.CharField(max_length=100, verbose_name='رقم السجل')),
                ('is_active', models.BooleanField(default=True, verbose_name='هل مسموع')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='سوفت دليت')),
                ('renewed_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='user.companylicense', verbose_name='تم تجديده من')),
            ],
            options={
                'verbose_name': 'السجل التجاري',
                'verbose_name_plural': 'السجلات التجارية',
            },
        ),
    ]
